{{- if .Values.backend.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "ekomart.backend.labels" . | nindent 4 }}
spec:
  type: {{ .Values.backend.service.type }}
  selector:
    app: backend
    {{- include "ekomart.selectorLabels" . | nindent 4 }}
  ports:
  - name: http
    port: {{ .Values.backend.service.port }}
    targetPort: {{ .Values.backend.service.targetPort }}
    protocol: TCP
{{- end }}
