apiVersion: v1
kind: Service
metadata:
  name: backend-metrics
  namespace: ekomart
  labels:
    app: backend
    monitoring: "true"
spec:
  selector:
    app: backend
  ports:
    - name: metrics
      port: 5000
      targetPort: 5000
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: backend-monitor
  namespace: ekomart
  labels:
    app: backend
    release: prometheus
spec:
  selector:
    matchLabels:
      app: backend
      monitoring: "true"
  endpoints:
    - port: metrics
      interval: 30s
      path: /metrics
