apiVersion: v1
kind: Secret
metadata:
  name: github-repo-ssh
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: git@github.com:bashairfan0911/E-commerce-Prod.git
  sshPrivateKey: |
    -----BEGIN OPENSSH PRIVATE KEY-----
    YOUR_SSH_PRIVATE_KEY_HERE
    -----END OPENSSH PRIVATE KEY-----
