apiVersion: v1
kind: Secret
metadata:
  name: github-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: https://github.com/bashairfan0911/E-commerce-Prod.git
  username: bashairfan0911
  password: YOUR_GITHUB_TOKEN_HERE
