apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: ekomart
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      name: backend
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: irfan8194/ecommerce-backend
        ports:
        - containerPort: 5000
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "5000"
        - name: DBURI
          value: "mongodb+srv://bashairfan518:Irfan86101@cluster0.hwcnddm.mongodb.net/ekomart?retryWrites=true&w=majority"
        - name: JWT_SECRET_KEY
          value: "TN3TY7aH4qVFwRgJHvlsmaATH8RrrTBH"
        - name: CLOUD_NAME
          value: "drukumhal"
        - name: CLOUD_API_KEY
          value: "517746727976313"
        - name: CLOUD_API_SECRET_KEY
          value: "EZmCUOotMuHeSwTx79ro8vuzt3k"
        - name: KEY_ID
          value: "your_razorpay_key_id"
        - name: KEY_SECRET
          value: "your_razorpay_key_secret"
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: ekomart
spec:
  type: LoadBalancer
  selector:
    app: backend
  ports:
  - name: http
    port: 5000
    targetPort: 5000
    protocol: TCP
