apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: ekomart
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      name: frontend
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: irfan8194/ecommerce-frontend:v1.11
          ports:
            - containerPort: 5173
          env:
            - name: VITE_API_PATH
              value: "http://3.17.156.212:31100"
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: ekomart
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
    - port: 5173
      targetPort: 5173
      protocol: TCP
      nodePort: 31000
