apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: ekomart
type: Opaque
stringData:
  DBURI: "mongodb+srv://your_username:your_password@cluster.mongodb.net/ekomart?retryWrites=true&w=majority"
  JWT_SECRET_KEY: "your_jwt_secret_key_here"
  CLOUD_NAME: "your_cloud_name"
  CLOUD_API_KEY: "your_api_key"
  CLOUD_API_SECRET_KEY: "your_api_secret"
  KEY_ID: "your_razorpay_key_id"
  KEY_SECRET: "your_razorpay_key_secret"
